config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "goods#index"
  resources :goods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/good.rb
class Good < ApplicationRecord
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end
class GoodsController < ApplicationController
  def new
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  #before_action :set_good, only: [:show, :edit, :update, :destroy]


def index
    @goods = Good.all
  end
  def new
    @good = Good.new
  end
  def create
   good = Good.create(good_params)
    good.user_id= current_user.id
    good.save
    redirect_to good
  end
  def destroy
    Good.find(params[:id]).destroy
    redirect_to goods_path
  end
  def show
    @good=Good.find(params[:id])
  end
  private
  def good_params
    params.require(:good).permit(:description, :name, :price, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goods/index.html.erb
<h1>Buy & Sell !!!</h1>

<%=link_to "Enter New Product", new_good_path %>


<% @goods.each do |good| %>


    <li><%= link_to good.name, "/goods/#{good.id}" %> </li>
<% end %>

app/views/goods/new.html.erb
<h1> New Product </h1>

<%= form_for Good.new do |good| %>
    <div>
        <label>Name:</label>
        <%= good.text_field :name %>
    </div>
    <div>
        <label>description:</label>
        <%= good.text_field :description %>
        <div>
        <label>Price:</label>
        <%= good.text_field :price %>
    </div>
    </div>
    <label>Picture:</label>
    <%=good.file_field :picture %>
    <%= good.submit %>
    
     <br> <br>
    
    <div><%=link_to "Main Menu", goods_path %></div>
<br> <br>
    
<% end %>

app/views/goods/show.html.erb
<div><%= @good.name %></div>


<br> <br>
<%= link_to "Delete", good_path(@good), 
method: :delete,
data:{confirm:"Are you sure"} %> <br> <br>

<div class="description"><%= @good.name %>
<%= @good.price %></div>

 <div>
        <label>description:</label>
        <%= @good.description %>
        </div>

        <label>Price:</label>
        <%=  @good.price %>

    <br> <br>
    
    <% if @good.picture.attached? %>
    <%= image_tag(@good.picture, height: 200, class: "good") %>
<% end %>
    
    <div><%=link_to "Main Menu", goods_path %></div>
<br> <br>
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ventas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    <%= yield %>
  </body>
</html>